---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscale.mongodb.io
  resources:
  - mongorouterautoscalers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscale.mongodb.io
  resources:
  - mongorouterautoscalers/status
  verbs:
  - get
  - patch
  - update
